name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: |
          npm install
          cd ./client
          npm install
      - name: Check Style
        run: npm run lint
      - name: Build Code
        run: "npm run build:ui"
      - name: Trigger Deployment
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
        run: curl $deploy_url
