name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: |
          npm install
          cd ./client
          npm install
      - name: Check Style
        run: npm run lint
      - name: Build Code
        run: "npm run build:ui"

      - name: Trigger Deployment
        id: deploy
        if: ${{ env.CONDITION == 'true' }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl $deploy_url

      - uses: sarisia/actions-status-discord@v1
        if: ${{ steps.deploy.outcome == 'success' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Deploy"
          description: "A new version of Phonebook deployed"
          username: Phonebook
      - uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build"
          description: "Build Failed for Phonebook"
          username: Phonebook

  version-tagging:
    needs: [deployment_pipeline]
    if: ${{ github.env.CONDITION == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: v
